services:
  redis-node-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-1
    hostname: redis-node-1
    ports:
      - "2211:22"
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.0.11

  redis-node-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-2
    hostname: redis-node-2
    ports:
      - "2212:22"
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.0.12

  redis-node-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-3
    hostname: redis-node-3
    ports:
      - "2213:22"
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.0.13

  redis-node-4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-4
    hostname: redis-node-4
    ports:
      - "2214:22"
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.0.14

  redis-node-5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-5
    hostname: redis-node-5
    ports:
      - "2215:22"
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.0.15

  redis-node-6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-6
    hostname: redis-node-6
    ports:
      - "2216:22"
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.0.16

  redis-node-7:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-7
    hostname: redis-node-7
    ports:
      - "2217:22"
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.0.17

  redis-node-8:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-8
    hostname: redis-node-8
    ports:
      - "2218:22"
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.0.18

networks:
  redis-cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24