[redis_masters]
redis-node-1 ansible_host=localhost ansible_port=2211 internal_ip=10.10.0.11
redis-node-2 ansible_host=localhost ansible_port=2212 internal_ip=10.10.0.12
redis-node-3 ansible_host=localhost ansible_port=2213 internal_ip=10.10.0.13

[redis_replicas]
redis-node-4 ansible_host=localhost ansible_port=2214 internal_ip=10.10.0.14 master_node=redis-node-1
redis-node-5 ansible_host=localhost ansible_port=2215 internal_ip=10.10.0.15 master_node=redis-node-2
redis-node-6 ansible_host=localhost ansible_port=2216 internal_ip=10.10.0.16 master_node=redis-node-3

[redis_nodes:children]
redis_masters
redis_replicas

[redis_nodes:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/redis_cluster_key
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no